### ISSUE TITLE
Own-Prefix Monitoring

### ISSUE THREAD

**Issue by TheBlueMatt** [NLnetLabs/routinator#110]
One (IMO legitimate) concern in several RIR communities is the possibility of malicious or incorrect modification of the RPKI database affecting routing policies (eg some RIPE members' concern of the possibility of local government orders effectively giving the Dutch government de-facto control over some aspects of routing policy or concern by ARIN's lawyers of RPKI misconfiguration resulting in legal trouble for the RIR organization itself). While not a significant risk today, as RPKI deployment begins in earnest in larger networks, ensuring these types of issues don't become the lowest-hanging fruit for censorship [1] or cybercrime and generally de-risking the possibility of bogus RPKI data resulting in routing issues should be seriously considered. One approach taken by the TLS/CA community to de-risk similar threats is to increase visibility through Certificate Transparency and automated monitoring. While RPKI data is inherently open, there are still some lessons to be learned here, namely:

 * Software like routinator should support automated monitoring of locally-known prefixes to make it easier to alert the operator of any change to the RPKI-enforced restrictions (much like some commercial services monitor CT logs to ensure no malicious certificates were issued for their domains).
 * RPKI Validators should cross-check data they receive from RIRs with other well-known copies (eg Cloudflare announced they were shoving RPKI data into a CT log at https://ct.cloudflare.com/logs/cirrus). This ensures that RPKI data is consistent globally in case of an RPKI server providing different data to different users (thus bypassing the monitoring in the first suggestion).

IMO there's some important de-risking that can be accomplished in similar manners with minor tweaks to RIR policy (eg delaying transfers/changes to ensure monitoring can detect issues before they reach router policy), but at least these are things that can be done locally and provide some easy wins.

[1] Personally, I'm very sympathetic to the concerns of some members in the RIPE community. The US-government-organized seizure of gTLD domain names through Verisign's presence in the US using civil asset forfeiture laws sets a dangerous precedent for number resources in the ARIN region (for those not in the US, these laws allow the government to seize assets under suspicions that they were gained or used in criminal activity with the "due process" occurring only after the fact, wherein the party who's assets they were has to sue the government to have them returned). Further, the current Australian regime's stance on cryptography and government orders dictating technology seems foreboding for number resources in the APNIC region.

**Comment by lspgn** [comment]
Hello,
My two cents as developer of the [Cloudflare RPKI Validator](https://github.com/cloudflare/cfrpki) that also pushes data to our [CT log](https://ct.cloudflare.com/logs/cirrus).

**Technically:**
Just a bit of context for people unfamiliar with CT reading this.
I would like to point that web certificates do not have a hierarchy (example.com can be present in certificates from two authorities), while IPs are supposedly attached to one RIR.
There can be [IPs transfers between region](https://www.ripe.net/manage-ips-and-asns/resource-transfers-and-mergers/inter-rir-transfers), which AFAIK are not involving IANA. This would make it harder to have a single root authority from IANA.
All the 5 RIRs root certificates contains 0.0.0.0/0 and ::/0. You have to look a few children certificates to see their current pool of IPs. I am assuming this is for simpler operational reasons (to avoid regenerating the root certificate?).

What I noted: the rollout of new certificates (especially for Manifest) is quite massive. Every day, thousands EE certificates are regenerated.

RPKI as of today is very centered within the RIR. They have the key, do the signing and own the infrastructure to distribute the data.
Some certificates authorities will have their own logs (DigiCert) and will push when they sign a new certificate.

On a monitoring point of view with the information above, seeing the same prefix on different regions should raise some red flags.

**Regarding Validators:**
After every validation, our internal validator saves historical data and pushes the certificates to CT. Since this is quite a heavy operation that is anchored with our internal tooling, and I did not want to bloat OctoRPKI, I made a [simple validator](https://github.com/cloudflare/cfrpki/tree/master/cmd/ctrpki) that just pushes to a log from a local directory that have been synchronized by a more complete validator.
Anyone can push certificate chains to Cloudflare Cirrus but the log will only accept if they have been signed by one of the five root.
One drawback of CT logs for RPKI is they are not accepting CMS data. I am only uploading up to the EE certificate contained in the CMS.
In order to keep this information, I am also building a historical database to be accessed in our [RPKI Portal](https://staging.rpki.cloudflare.com). I chose also to collect only certs and ROAs since their data is more critical and also less massive.

In my opinion, it is not the role of validators to do a whole check of this data. We are also talking about 50k+ (and growing) unique resources that need to be verified at runtime.
It would not be as simple as a Chrome extension for the current visited website.
I am not sure how to determine a "well-known copy" since they are directly distributed (RRDP+rsync+manifest files).
What is in our CT log is the "Cloudflare view". An other view could also be valid.

In the web, TLS sessions can hijacked/MITM by proxies or ISPs and injecting a fake certificate for a domain they signed with another authority.
If a certificate is valid, the browser does not know if it has been maliciously signed or is just a configuration of the website operator (cryptographic requirements, pricing, country obligations...). The log of certificates is useful whenever an authority should be banned from a browser. The browser use leverage of their user base for the CA to make money.

For a RPKI certificate hijack: that would mean hijacking one of the root keys and then hijacking/MITM either the RRDP or rsync (the latter would be easier since it is cleartext) OR taking ownership of the RIRs' distribution. It would likely require signing Manifest files as well.
A maliciously signed certificate would cover some sub-IP space and could be logged.
But, banning a certificate authority is not really realistic as it would block the IPs in the region to be signed.
Furthermore, it is unclear on who should be taking the decision on this? The validator dev? The operators of the validator? The RIRs?
The people who signed would not have an alternative to sign their IPs in another region.
On the contrary, having only 5 RIRs can also help target the source of the problem and publicly pointing out issues.

Lastly, CT is just a database. There need to be tooling around it in order to provide checks and indexing the certificates. I am thinking of [Google](https://transparencyreport.google.com/https/certificates?hl=en) or [CRT](https://crt.sh/).
Once again, I do not think this is the validator's job to provide such services since the infrastructure to maintain such service is important.

I am probably raising more questions than solving them. I am all in favor for monitoring using CT but I think the amount of actions that can be taken following a malicious signing are limited.

**Comment by TheBlueMatt** [comment]
Some thoughts provided inline:

> On a monitoring point of view with the information above, seeing the same prefix on different regions should raise some red flags.

Interesting thought. Probably worth adding a warning in routinator for that, assuming there isn't already one.

> In my opinion, it is not the role of validators to do a whole check of this data. We are also talking about 50k+ (and growing) unique resources that need to be verified at runtime.

Not sure what your point here is? Are you suggesting validators shouldn't validate the full historical record of RPKI updates? That makes sense to me and isn't what I was suggesting, as, indeed, its overkill and I'm not sure what kind of attacks it would prevent.

> I am not sure how to determine a "well-known copy" since they are directly distributed (RRDP+rsync+manifest files).
> What is in our CT log is the "Cloudflare view". An other view could also be valid.

The point of RPKI is that it should be globally-consistent. If I have a different view than Cloudflare does (especially as it relates to my own prefixes), this is an indication of one of three things:
 * I pulled the database at a different time and the differences should resolve themselves soon,
 * Cloudflare or my RPKI validator are having issues fetching the latest data (a condition which indicates that I should go investigate, especially if I'm comparing against several public copies and disagree with several of them), or
 * the RPKI repository is giving different people different copies, an indication that something very seriously wrong is occuring.

If a validator can cheaply compare its validated state against the validated view of several other validators (which is easy to do), then they absolutely should, especially if you're relying on RPKI to inform key routing decisions.

>  A maliciously signed certificate would cover some sub-IP space and could be logged.

I'm suggesting precisely that we implement such things, as, to my knowledge, outside of maybe Cloudflare, no such thing is implemented. Especially if its for your own IP space!

> But, banning a certificate authority is not really realistic as it would block the IPs in the region to be signed.
> Furthermore, it is unclear on who should be taking the decision on this? The validator dev? The operators of the validator? The RIRs?

Sure, you couldn't ban the CA, but you could do the next best thing: stop using it to validate (the prefixes in question). Falling back on today's system seems for the prefix in question to be the correct action in any of these cases, at least until some resolution is achieved.

>  On the contrary, having only 5 RIRs can also help target the source of the problem and publicly pointing out issues.

I think maybe we agree more than is obvious. My point is precisely that adding simple tooling to improve detection and logging of issues is key here, so that operators can take manual corrective action.

> Once again, I do not think this is the validator's job to provide such services since the infrastructure to maintain such service is very large.

True, but something as simple as "has anything changed with my prefixes from the following list?" would go a long ways, at least for local operators.

> I am probably raising more questions than solving them. I am all in favor for monitoring using CT but I think the amount of actions that can be taken following a malicious signing are limited.

Again, I think we're in agreement here. There isn't a lot of obvious corrective action that could be taken automatically, I'm mostly just suggesting we take steps towards better, automated, pervasive monitoring of a system that is slowly being deployed at the core of key infrastructure.

**Comment by partim** [comment]
We’ve been already looking into monitoring and alerting etc. Our thinking currently is to only have very basic monitoring as part of Routinator itself – mostly information relating to the proper functioning of Routinator – and provide facilities for extensive analysis externally.

I understand and agree that you want to have readily available solutions that just do their thing, but you can already build monitoring for your own prefixes based on the CSV output from Routinator and a little bit of scripting.

We are likely to do something more in this area, but obviously we have to make do with the resources we have.

**Comment by lspgn** [comment]
> > In my opinion, it is not the role of validators to do a whole check of this data. We are also talking about 50k+ (and growing) unique resources that need to be verified at runtime.
> 
> Not sure what your point here is? Are you suggesting validators shouldn't validate the full historical record of RPKI updates? That makes sense to me and isn't what I was suggesting, as, indeed, its overkill and I'm not sure what kind of attacks it would prevent.

My apologies, I misunderstood as CT logs were mentioned.

> > I am not sure how to determine a "well-known copy" since they are directly distributed (RRDP+rsync+manifest files).
> > What is in our CT log is the "Cloudflare view". An other view could also be valid.
> 
> The point of RPKI is that it should be globally-consistent. If I have a different view than Cloudflare does (especially as it relates to my own prefixes), this is an indication of one of three things:
> 
> * I pulled the database at a different time and the differences should resolve themselves soon,
> * Cloudflare or my RPKI validator are having issues fetching the latest data (a condition which indicates that I should go investigate, especially if I'm comparing against several public copies and disagree with several of them), or
> * the RPKI repository is giving different people different copies, an indication that something very seriously wrong is occuring.

I do not believe RPKI **must** be globally consistent. Today, per the validation specification, it does not make sense to have diverging repositories.
I agree, the actual distribution protocols may cause some discrepancy depending on when you query/validate. This is a side effect of having a bazillion files that can be added or deleted independently with two different protocols (rrdp/rsync).
It actually can cause some issue as the turnover of certificates is quite high and revocations lists are heavily used (the biggest files are a CRL and a Manifest of half a MB `rsync://rpki.ripe.net/repository/DEFAULT/HGp1AESLbyiopScGy7yW4b6s_T4.crl` and `rsync://rpki.ripe.net/repository/DEFAULT/HGp1AESLbyiopScGy7yW4b6s_T4.mft`).
I've seen validators diverging in the data they produce due to this until it converges back few hours later (or not at all).
This is why I think it should handle inconsistencies even though it does not bring any use case (don't get me wrong, I would love to have one unique blob per RIR to do validation on).
Nonetheless the cryptography will prevail in any case for the validation and is not necessarily meaning of something wrong.

> If a validator can cheaply compare its validated state against the validated view of several other validators (which is easy to do), then they absolutely should, especially if you're relying on RPKI to inform key routing decisions.

Yes, I will join @partim opinion. This is also one of the reason we publish our list of prefixes to say "this is what our routers validate on".
But why should anyone trust our list?

> > A maliciously signed certificate would cover some sub-IP space and could be logged.
> 
> I'm suggesting precisely that we implement such things, as, to my knowledge, outside of maybe Cloudflare, no such thing is implemented. Especially if its for your own IP space!
> 
> > But, banning a certificate authority is not really realistic as it would block the IPs in the region to be signed.
> > Furthermore, it is unclear on who should be taking the decision on this? The validator dev? The operators of the validator? The RIRs?
> 
> Sure, you couldn't ban the CA, but you could do the next best thing: stop using it to validate (the prefixes in question). Falling back on today's system seems for the prefix in question to be the correct action in any of these cases, at least until some resolution is achieved.

I think there was some confusion between the certificates and validated data (CSV/JSON list of prefixes) and I diverged from the original question. The validated data is easier to compare with historical records. Certificates, not so much. They embed much more information and in the future, not just prefixes.

Do you mean for a handful of prefixes: stop using RPKI?
But a certificate scope will extend way beyond those prefixes. And you cannot enforce this without another source of truth.

Having a fallback (let's say: IRR) can work, but it must serve the same purpose or have the same meaning (which I am not sure IRR does). Plus, it could be an attack vector to make the CA be untrusted.

> > On the contrary, having only 5 RIRs can also help target the source of the problem and publicly pointing out issues.
> 
> I think maybe we agree more than is obvious. My point is precisely that adding simple tooling to improve detection and logging of issues is key here, so that operators can take manual corrective action.
> 
> > Once again, I do not think this is the validator's job to provide such services since the infrastructure to maintain such service is very large.
> 
> True, but something as simple as "has anything changed with my prefixes from the following list?" would go a long ways, at least for local operators.

I agree and will also take this suggestion for GoRTR: it already computing diffs of the JSON data it receives.
Just reinforcing the fact that it's the responsibility of the prefix owner to make sure his data reaches his validator (and potentially others validators). But the action that one can take on other's people network is limited (as RPKI is not an absolute ACL).
If my personal validator were to cross-check with others, then the idea behind RPKI being a source of truth is removed.
When Cloudflare sign its prefixes, its source of truth is local, then for the rest of the world, it's the RIR the IPs are on. Cloudflare should not and cannot enforce its local source of truth for everyone.

**Comment by jmaurice** [comment]
Taking a bit from DNSSEC, one idea which we could base an IP web of trust on is to start with a "root zone" file where each /8 prefix gets delegated from the root zone file to either the legacy holder, or to the RIR to which it is allocated. From there, the RIR could issue a cryptographically signed certificate for X years, cryptographically delegating it to the LIR or NIR or end-user. The end-user could then issue their own cryptographic certificate which authorizes particular ASNs to announce or whatever routing policies.

**Comment by partim** [comment]
Apart from the messy trust anchor situation, that is pretty much what RPKI does. Currently, the RIRs serve as trust anchors only. This is fine for most IP space except legacy space. The common solution is to move it into one if the RIRs.

That all (well, except one) end-user certificates and objects are issued via an RIR or NIR system is more a practical issue. It was done initially to get any uptake at all (Why would you bother with running a CA and publishing data when there is zero benefit for you as an early adopter?). For most people, it is a rather practical solution, though. Because you are trusting the RIR or NIR with not messing with your resources, it is also kind of okay from a security perspective.

**Comment by partim** [comment]
I’m not sure there is any concrete action to be taken from the discussion – other than that we all agree we need more tooling for monitoring and analyzing the RPKI dataset – so I will close the ticket. Feel free to reopen it if there is more to discuss!
