### ISSUE TITLE
filter-prefix doesn't check subnet size?

### ISSUE THREAD

**Issue by devicenull** [NLnetLabs/routinator#155]
I'm not sure if this is the intended behavior or not:

consider a request to: /json?filter-prefix=208.167.225.0/29
<pre>
{
  "roas": [
    { "asn": "AS46407", "prefix": "208.167.225.0/24", "maxLength": 24, "ta": "arin" },
    { "asn": "AS20473", "prefix": "208.167.224.0/19", "maxLength": 24, "ta": "arin" }
  ]
}
</pre>

I would not expect that query to return anything, as a /29 is smaller then the /24 maxLength there.

However, looking at the results for /json?filter-prefix=208.167.225.0/23
<pre>
{
  "roas": [
    { "asn": "AS20473", "prefix": "208.167.224.0/19", "maxLength": 24, "ta": "arin" }
  ]
}
</pre>
Which is correct (the extra /24 is not shown)

**Comment by partim** [comment]
The prefix filter returns all VRPs that cover the provided prefix. That is, the VRP prefix length is less or equal to the route prefix length. This is different from the prefix being matched by the VRP which requires the ASN and max length to also fit.

In order to determine the RPKI state of a route prefix, you need all covering VRPs. If there is none, it is unknown. If there is at least one covering VRP but no matching VRPs, it is invalid. If there is at least one convering VRP and at least one matching VRP, it is valid.

So in your first example, the provided prefix would be RPKI invalid because there is two covering VRPs but none of the match because of the smaller max length. In your second example, the prefix would be RPKI valid if announced by AS20473.

**Comment by AlexanderBand** [comment]
For reference: https://tools.ietf.org/html/rfc8416#section-3.3.1

**Comment by devicenull** [comment]
Ah, perhaps this should be a feature request.  We're migrating from RIPE's RPKI validator, which has a validity endpoint.  This takes a prefix and ASN, and returns either 'VALID', 'INVALID_ASN', or 'INVALID_LENGTH'.

While the logic to do this client-side isn't too bad, this seems like something that would be useful to have in routinator.

**Comment by partim** [comment]
We were actually discussing adding that yesterday. So this might happen rather soon …
