### ISSUE TITLE
rsync error

### ISSUE THREAD

**Issue by XioNoX** [NLnetLabs/routinator#184]
See logs bellow, that's with 0.5.0 and previous version.
Not sure if it's related to Routinator or some downstream RPKI repo.
```
Jul 18 15:27:24 rpki1001 routinator[23681]: rsync://59e6c66f3466/rpki: bad response from proxy -- HTTP/1.1 503 Service Unavailable
Jul 18 15:27:24 rpki1001 routinator[23681]: rsync://59e6c66f3466/rpki: bad response from proxy -- HTTP/1.1 503 Service Unavailable
Jul 18 15:27:24 rpki1001 routinator[23681]: rsync://59e6c66f3466/rpki: rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
```

Note that we use proxies, but that's the only rsync that seems to fail, and running the command locally (without proxies) returns an obvious:
```
rsync rsync://59e6c66f3466/rpki
rsync: getaddrinfo: 59e6c66f3466 873: Name or service not known
```

**Comment by AlexanderBand** [comment]
Hi Arzhel, I've seen this pop up several weeks ago as well and I think most users have if they dig in their logs. 

Someone has configured a repository incorrectly somewhere at least for a while; this is not related to Routinator itself. Clearing out your repository directory (by default `~/.rpki-cache/repository/`) and restarting will definitely clear the error. 

However, since we thought this behaviour was annoying too, we now delete the data for rsync modules that aren’t referenced anymore since 0.5. So if this doesn't disappear by itself eventually, we may have a bug.

**Comment by XioNoX** [comment]
Indeed, thanks! Everything went back to normal 1h after the upgrade to 0.5.0 as shown on https://grafana.wikimedia.org/d/UwUa77GZk/rpki?orgId=1&from=1563464268870&to=1563472364723
