### ISSUE TITLE
Dependency Graph has Grown Huge

### ISSUE THREAD

**Issue by TheBlueMatt** [NLnetLabs/routinator#225]
Installing the latest routinator pulls in over 200 dependencies, and it seems to keep growing, which has started to become incredibly concerning for a key component of securing Internet infrastructure. It would be nice to have a few feature flags to turn off building optional components to cut down on threat surface area, though obviously removing some dependencies wholesale would be much better.

**Comment by partim** [comment]
I understand – and to a degree share – your discomfort, but I am not sure if the number of dependencies is a good metric here. For one, keep in mind that you see all the transitive dependencies that you wouldn’t see in C land where you build your libraries – and consequently their dependencies – separately.

In addition, because dependency management is such a smooth process in Rust, there is a tendency to build smaller, single purpose crates instead of large, feature-rich libraries. Obviously, this leads to an overall bigger number of dependencies. But these smaller crates are often used by multiple of the crates further up and actually decreasing the overall amount of code.

When it comes to bugs and vulnerabilities, code reuse is actually a good thing. By using popular libraries instead of rolling your own code, you get all the vetting that has been done for those libraries for free. We used to have our own HTTP implementation. Switching that out for hyper, which likely accounted for the largest growth in dependencies, made the HTTP server more robust and improved its performance. The other big library in terms of dependency use is reqwest, an HTTP client library used for RRDP – and I really don’t want to roll my own.

As for features, I don’t think there is much that could be turned off. Perhaps SLURM if you don’t use local exceptions, but that’s just a single dependency. Perhaps the HTTP server, but (a) you would loose monitoring and I don’t think you’d want that and (b) part of its dependencies are also used by the RTR server and the HTTP client, so I am not sure how much that would actually save, even if we’d make it possible to build without server mode entirely.

**Comment by TheBlueMatt** [comment]
Right, no question sharing code is, in general, a good idea. Sadly, however, its not a given that a dependency is going to get a lot of eyes. Worse still, the current routinator dependency graph depends on at least two different versions of many crates, which kinda negates the argument - if your dependency can't even keep its dependencies up to date, suggesting they're more secure and better written is definitely not true.

Worse yet, using standard cargo dependencies means your users are inherently trusting crates.io *and* github to serve honest, unmodified copies of the code. At least vendoring dependencies would improve things greatly.

Further, lots of rust crates can sometimes introduce other issues - eg the new use of rustls has resulted in routinator no longer working on non-ARM, non-x86 devices (eg POWER, which I use all the time), due to the transitive dependency on ring.

**Comment by partim** [comment]
Sorry for the silence, I didn’t realize it has been 26 days.

I’ll respond to your arguments soon, but for your concrete problem: I have made a branch `tls-via-features` that allows selecting the TLS implementation via features. It also switches to `native-tls` by the default – which increases the dependency count, but actually only uses the crates relevant for the platform. Does that fix the compile issue?

**Comment by TheBlueMatt** [comment]
Thanks. That would fix the issue, but it looks like now the MSRV is 1.39, so I can't use routinator anymore (Debian and rustup seems to still be serving a completely unauthenticated toolchain, which is unacceptable for security-critical software).

**Comment by partim** [comment]
With the code hopefully having settled a fair bit now, I have looked at the dependency list again. But it turns out that almost all dependencies we have are necessary for basic RPKI processing. Basically, the only thing that would cut back on dependencies if hidden behind a feature flag would be SLURM support and that would ultimately only be one or two crates. I don’t think it is worth adding the maintenance overhead for that.

So, I think it is probably time to admit that the dependency count is what it is and that there isn’t much we can do about it. As such, I am closing the issue now.

**Comment by TheBlueMatt** [comment]
This issue should probably be reopened. Since closure the dependency graph has grown even more, and the immediate issue of depending on `ring` has been reintroduced, this time non-optionally and directly.

**Comment by TheBlueMatt** [comment]
Also, it looks like some dependencies with solo maintainers have creeped in. At least `log-reroute` appears to be a solo maintainer crate with very little outside contributions, implying its also relatively unreviewed on a regular basis. It may make sense to vendor that.

**Comment by partim** [comment]
Fair point on `log-reroute`. I have created #732 for the matter.

Looking over the remaining direct dependencies, they seem to all the be well-used and mostly part of what you could call the standard crate set.

As for `ring`, it is the crypto library we are using, so using it in the same version as rustls (and using rustls rather than OpenSSL) makes sense to me.

**Comment by TheBlueMatt** [comment]
Right, the original context of this issue was also that I was unable to build routinator on my normal workstation because its not x86/arm, which is all that `ring` supports. That's okay, though, just means I can't use routinator, but I had already moved to rpki-client because of the dependency graph of routinator being so huge.
