### ISSUE TITLE
Wrong port (3323/tcp instead of 323/tcp) in README

### ISSUE THREAD

**Issue by schadom** [NLnetLabs/routinator#29]
According to RFC6810:

https://tools.ietf.org/html/rfc6810#section-12

	IANA has assigned 'well-known' TCP Port Numbers to the RPKI-Router
	Protocol for the following, see Section 7:

		rpki-rtr
		rpki-rtr-tls

https://tools.ietf.org/html/rfc6810#section-7

	Caches and routers MUST implement unprotected transport over TCP
	using a port, rpki-rtr (323)

	Caches and routers MAY use TLS transport [RFC5246] using a port,
	rpki-rtr-tls (324);

Please follow the standards, thanks.

**Comment by partim** [comment]
The reason we've chosen 3323 as the default is that 323 is a privileged port and you need to be root or an otherwise privileged user to bind to that port. Since there is no other reason to run Routinator as root, we decided to pick a non-privileged port as default. Note that, for security reasons, the default address is 127.0.0.1, too, so you can't connect to a Routinator with this default configuration, anyway.

This is explained in the README, admittedly in a bit of a throw-away fashion. Would you prefer we made this more clear?

**Comment by schadom** [comment]
Thanks for the detailed info.

>This is explained in the README, admittedly in a bit of a throw-away fashion. Would you prefer we made this more clear?
Yes would be great! Thanks

**Comment by mahtin** [comment]
Sorry ... this 2018 (and soon to be 2019); Who in their right mind is running non-tls connections. The default should be tls (port 323) with active configuration edits needed to downgrade to non-tls (port 3223).

Reread https://www.internetsociety.org/blog/2018/03/75852/ if you want.

**Comment by partim** [comment]
TLS is definitely planned for one of the next releases. However, we haven't heard from anyone who wants TLS, I am not even sure routers support it. People seem to prefer the SSH transport, probably because authentication is easier to configure.

**Comment by job** [comment]
I'm more rooting for RTR-over-SSH, since there already are implementations, and this doesn't require the validator implementer to do any work, they just need to update the README that some SSH daemon should be installed.
