### ISSUE TITLE
Routinator won't listen on all IPv6 enabled interfaces

### ISSUE THREAD

**Issue by racompton** [NLnetLabs/routinator#325]
Hi, I'm trying to run the routinator process to listen on all IPv4 and IPv6 addresses.  I'm able to get it to listen to all interfaces for IPv4 but not IPv6.  I'm running the following routinator command:
/home/routinator/.cargo/bin/routinator -v -b /opt/routinator server --http 127.0.0.1:8080 --rtr 0.0.0.0:8323 --rtr [::]:8323
but it's only listening on IPv4:
sudo lsof -i -n -P | grep 8323
routinato 23541 routinator    3u  IPv4 756991      0t0  TCP *:8323 (LISTEN)

**Comment by partim** [comment]
On Linux, there is some kind of overlap between IPv4 and IPv6. You can’t bind to all interfaces on both on the same port. There should be an ‘address already in use’ warning in your log.

However – and again: on Linux – IPv6 includes IPv4, so you only need to bind to `--rtr [::]:8323`.

Note that starting with 0.7.0, Routinator will exit on these kinds of errors instead of happily running with what it got.

**Comment by racompton** [comment]
Thanks for the reply.  I validated that this is working.
