### ISSUE TITLE
unable to change rsync command with arguments

### ISSUE THREAD

**Issue by kruisdraad** [NLnetLabs/routinator#355]
The rsync command in the configuration does not accept any arguments, in my case i want to force IPv4, when doing that it tests if ' rsync -4' is a valid command and returns:

Failed to run rsync: No such file or directory (os error 2)

Use case: a linux router that require a specific binding of IP address
Suggestion, use basename for exec testing.

Also when you change it to true, it just assumes a rsync was done?

**Comment by partim** [comment]
I suspect you will have to provide the full path to rsync, i.e., `/usr/bin/rsync`. Routinator doesn’t run the command through a shell, so the `$PATH` won’t be respected.

Yes, using `true` (or, rather, `/usr/bin/true`) will indeed result in Routinator assuming rsync was successfully done. Except for server mode, you can achieve the same result with the `--noupdate` option.

**Comment by kruisdraad** [comment]
I noticed that there was a option for args, but its not listed in :

routinator config

blank values like http-listen are shown, i suggest adding all options in there. My issue was that i did not had a default config file and used this as a basis.

additionally the help does not show the rsync-args, only command and timeout.

**Comment by AlexanderBand** [comment]
When I look at the log output I see for example:

```
rsync://repository.lacnic.net/rpki: Running command "rsync" "--contimeout=10" 
"--timeout=300" "-rltz" "--delete" "rsync://repository.lacnic.net/rpki/" 
"/home/nlnet/.rpki-cache/repository/rsync/repository.lacnic.net/rpki/"
```

Using that as a starting point, I added this line to the config file:
`rsync-args = [ "-4", "--contimeout=10", "--timeout=300", "-rltz","--delete" ]`

This seems to work.

**Comment by kruisdraad** [comment]
yes, thats what i said, only -4 even with --address works.

but the option is not listed in --help

**Comment by AlexanderBand** [comment]
Thanks I'll make sure to document this.

**Comment by partim** [comment]
The reason it doesn’t appear in `--help` is that the `rsync-args` option is only available in the configuration file, not as a command line option.

The reason it doesn’t appear in the output of `routinator config` is that there is a difference between it being empty and it being not present. If it is missing, Routinator tries to figure out whether to use a `--conntimeout` or not. If it is present – empty or otherwise –, this mechanism is skipped and the arguments are used as provided.

Both the option and this behaviour or documented in the manual page.

**Comment by AlexanderBand** [comment]
> Thanks I'll make sure to document this.

https://github.com/NLnetLabs/rpki-doc/commit/d9807cc26bec41777f3b3d0fc4bdf899ea85827e
