### ISSUE TITLE
Time is a monotonically increasing counter, except in routinator?

### ISSUE THREAD

**Issue by morrowc** [NLnetLabs/routinator#361]
While messing about with routinator in a 'deployed a bunch like seeds..' deployment I want to track whom has the latest view for some stats/etc. I noticed that at times instances appear to hop back in time? I didn't see their tardis, so i'm suspicious ? I can see this if I do something simple like:

$ for d in $(seq 1 10); do echo -n "${d}: " ; wget -O - -q http://localhost:9090/status  | grep last-update-start-at; sleep 2; done
1: last-update-start-at:  2020-06-30 05:10:15.002990787 UTC
2: last-update-start-at:  2020-06-30 05:10:15.002984862 UTC
3: last-update-start-at:  2020-06-30 05:10:15.002984770 UTC
4: last-update-start-at:  2020-06-30 05:10:15.002983475 UTC
5: last-update-start-at:  2020-06-30 05:10:15.002984781 UTC
6: last-update-start-at:  2020-06-30 05:10:15.002983366 UTC
7: last-update-start-at:  2020-06-30 05:10:15.002983420 UTC
8: last-update-start-at:  2020-06-30 05:10:15.002984646 UTC
9: last-update-start-at:  2020-06-30 05:10:15.002983295 UTC
10: last-update-start-at:  2020-06-30 05:10:15.002983428 UTC

note that in this case, the last-update goes backwards in time between 1 and 2, and 2 and 3, and 3 and 4, and 5 and 6 .. a bunch, this seems wonky.

I apologize for not providing a fix, my rust skillz suck rocks :( and I don't really know your codebase enough to poke meaningfully :(

what's going on here? how is time seemingly going backwards?

**Comment by partim** [comment]
This is an artifact of how these times are calculated. We keep the update start and end times around as something that the Rust standard library calls _instant._ These are opaque timestamps that can only be compared and subtracted to get a duration but not converted into wall clock.

So, when we need the wall clock for those outputs, we determine the duration between those times and now and then subtract that from the current wall clock time. The resulting may be slightly off. I suspect there could simply by rounding errors resulting from the clock granularity. Additionally, time keeping isn’t quite constant due to NTP adjustments or just the inherent unpredictability of virtual machines.

I should probably change the code to not show the sub-second part of the time. It doesn’t have much meaning, anyway.

**Comment by morrowc** [comment]
ah :) ok, I was thinking it was either some wonky rust impreciseness or maybe the VM behaviors. I think my ntp sync is 'hourly' (via ntpdate) on this example system.

I can run the routinator for a bit on a bare-metal box (no vm) and see if the behavior is the same... would that help?

**Comment by partim** [comment]
Honestly, I am not too worried about it. The discrepancies are within 10 microseconds within purely informational data.

**Comment by morrowc** [comment]
ok, so.. it's actually important though :)
If you have several routinator instances running and you care to collect the json/rpsl/etc data from the most updated one, times that go backwards are problematic.

Yes, I could parse the time and drop anything after seconds, but...
(and I guess I have to parse the time anyway... but...)

**Comment by partim** [comment]
Let me change the code and store a UTC date-time instead of an instant. There isn’t really a reason for the current implementation, I suspect it just happened.

**Comment by brada4** [comment]
It is not RTC or monotonic anything, it is constant time from last refresh that has varying interpretation.

**Comment by morrowc** [comment]
" it is constant time from last refresh that has varying interpretation."

wow, what? it's displayed as a time since... which seems to go backwards at times.
that's a curious interpretation.

(I think storing a UTC timestamp seems sane though, thanks!)

**Comment by brada4** [comment]
I dont think routinator existed 2020 years ago when your system's time intervals started. The format gives me impression it is UTC timestamp.
