### ISSUE TITLE
Simplify init step when using a deb package?

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/routinator#374]
The deb packages produced by the work done for PR #360 raised some questions concerning the fact that post-installation a user is required to manually run the following command:

```
sudo -u routinator routinator --config /etc/routinator/routinator.conf init --accept-arin-rpa
```

This is unwieldy and error prone. Can and should we make this easier?

Also, if at any time later the user invokes Routinator manually at the command line, if they aren't explicit about the user and config file to use then Routinator will not use the configuration settings defined in /etc/ meaning that it won't use the same the TAL and cache directory locations that the daemonized Routinator service uses. Is this a problem? Are the use cases for daemonized use and one-off invocation sufficiently different that you would not want them to use the same settings, input files and cached data?

Routinator only currently looks in the explicit paths provided on the command line or otherwise [falls back to default locations in the users $HOME directory](https://github.com/NLnetLabs/routinator/blob/aa767f4fe474efba7217c06951979afc1dc8c6e8/src/config.rs#L912).

**Comment by partim** [comment]
We have #368 already that will allow you to drop the `sudo -u` bit at least.

For the `--config` part I don’t have a good solution. I don’t want Routinator to automatically pick up `/etc/` files since that will lead to problems if Routinator is run as a regular user (in which case it should keep the repository local even if there is a global config to avoid file permission issues).
