### ISSUE TITLE
questions about routinator syncs certificates

### ISSUE THREAD

**Issue by syysumuro** [NLnetLabs/routinator#479]
hello，
      I installed routinator on my Ubuntu system，and try to use it to synchronize RPKI repositories. I found that it takes about 10 minutes to synchronize the entire  RPKI repositories and verify the certificates，is 10 minutes normal? I'd like to know how long this software will take to synchronize all RPKI repositories and validate all certificates respectively. 
     Whether the software will traverse all repositories during an update cycle? Is it traversing all of the RPKI certificates from the five RIRs' root certificates (default trust anchor) to leaf certificates to  synchronize RPKI repositories？

**Comment by AlexanderBand** [comment]
Typically the first validation run will take between 10 and 20 minutes, so what you're seeing is quite normal. In subsequent runs only the deltas will be processed so that is much quicker, typically around a minute or two. 

Relying party software will connect to the five RIR trust anchors and traverse the entire RPKI tree, which currently consists of about 25 individual repositories. That means fetching data is the slowest part of the validation process. 

You can learn more about this on rpki.readthedocs.io or discuss experiences on our [mailing list](https://lists.nlnetlabs.nl/mailman/listinfo/rpki).
