### ISSUE TITLE
Question about Routinator sync time

### ISSUE THREAD

**Issue by yehonglin929** [NLnetLabs/routinator#483]
Hello, I have used your tool to synchronize RPKI repositories, and I noticed that since there are only a few repositories for now, the fetching procedure is very fast. I wonder when every one manages their own repository (that means the number of repositories will increase a lot) or every ISP in the network deploys RPKI (that means the number of data being fetched will increase a lot) in the future, will the sync time increase a lot?

**Comment by AlexanderBand** [comment]
Hello! There are currently about 25 individual RPKI repositories that relying party software needs to sync from. Because with each validation run only the differences (deltas) need to be processed, the overall times it takes is not that long. 

Still, as a community it would be wise that not each Certificate Authority (CA) has their own publication point. This is why more and more, RPKI publication is offered as a service. For example, the more than 600 individual CAs in Brazil all publish to a single publication point offered by their parent, NIC.br. Recently, APNIC recently started offering this service too, and other RIRs have this on their roadmap. Lastly, 3rd parties such as cloud providers can offer RPKI publication as a service as well, which we're likey to see appearing over the course of this year. 

APNIC wrote a [blog post](https://blog.apnic.net/2020/11/20/apnic-now-supports-rfc-aligned-publish-in-parent-self-hosted-rpki/) with more information on this topic.
