### ISSUE TITLE
unattended-upgrades on Debian Buster fails

### ISSUE THREAD

**Issue by cnkk** [NLnetLabs/routinator#508]
Hi,
we are using [unattended-upgrades](https://packages.debian.org/buster/unattended-upgrades) on Debian Buster to upgrade our packages, but it fails to handle the routinator package.

How to reproduce:

1. Downgrade the routinator package
2. Manually trigger the unattended-upgrade package
`/usr/bin/unattended-upgrade -d --apt-debug`
 Output: [unattended-upgrade.log](https://github.com/NLnetLabs/routinator/files/6310690/unattended-upgrade.log)

We notice that the main error seems to be the following lines:
```
tar: ./etc/routinator/routinator.conf: Not found in archive
tar: Exiting with failure status due to previous errors
```

But upgrading the package manually works.
We did not observe this kind of behavior with any other package so far.

Any ideas?

**Comment by cnkk** [comment]
Hi,
i was able to find out some more information about this:

When using the default config `/etc/routinator/routinator.conf` everything works fine.
But we are not using the default one, so the original file and our file differ.

As the unattended-upgrade output says:
```
conffile line: /etc/routinator/routinator.conf a2fc42b04dc36bb109918396907fd4f7
current md5: f196c65c8620f3201363b50c701d208e
tar: ./etc/routinator/routinator.conf: Not found in archive
tar: Exiting with failure status due to previous errors
```

I looked into the docs of the [Cargo helper](https://github.com/mmstick/cargo-deb) which creates the Debian packages, but as far as I understand the docs everything seems to be configured correctly.

**Comment by ximon18** [comment]
Hi @cnkk,

So, if I understand correctly, you edited the config file and then on unattended upgrade there is nobody around to ask what to do about the fact that your config file differs to the one in the new package (because the MD5 sums of the config files don't match as shown by the log fragment).

After a bit of Googling I found [this ask ubuntu answer](https://askubuntu.com/a/921166) which I assume is configuring unattended upgrades with your preference for how to handle this situation. This would seem to be a standard mechanism for handling such conflicts and so would it be fair to think there's nothing we need to do in the Routinator DEB package and that users of the package should use this standard mechanism to handle this scenario?

I'm not an expert with Debian packaging so my apologies if I misunderstood and we need to iterate on this a bit more.

Ximon

**Comment by cnkk** [comment]
Hi @ximon18,

the dpkg options provided in the link helped to solve this problem.
I assumed because of [this](https://github.com/NLnetLabs/routinator/blob/main/Cargo.toml#L88) line, there should not be a problem to have a custom configfile.

But anyway, thanks for helping!
