### ISSUE TITLE
Offer Redhat Package Manager (RPM) packages for Routinator

### ISSUE THREAD

**Issue by AlexanderBand** [NLnetLabs/routinator#513]
Much in the same way as we offer packages for Debian/Ubuntu on [packages.nlnetlabs.nl](https://packages.nlnetlabs.nl).

**Comment by ximon18** [comment]
When we added Debian packaging support we made use of the existing [`cargo deb` ](https://github.com/mmstick/cargo-deb/) Rust cargo command. As `cargo deb` does NOT use the standard Debian packaging tools but instead generates the DEB file itself, we couldn't use the standard debhelper autoscripts (e.g. [this one](https://github.com/Debian/debhelper/blob/master/autoscripts/postinst-systemd-enable)) so we had to decide: write systemd unit management logic into our Debian pre/post install scripts ourselves, use stock Debian packaging tools, or extend cargo deb to handle systemd units. We chose the latter, partly because which commands to run in which part of the DEB packaging lifecycle seemed a bit complicated and thus risky to write by hand, and partly because we like to give back to the community so extending cargo-deb to handle the official autoscripts seemed like a nice thing to do. `cargo deb` now "just works" for Routinator and Krill installation of systemd units via Debian packages.

Now with RPM support we potentially face a similar issue. I did a proof-of-concept a while ago using `cargo generate-rpm` and building an RPM that install some files is pretty easy. However, we'd face the same issue as for RPMs there are so-called 'scriptlets' which handle systemd unit setup (see [this](https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd) and e.g. [this](https://cgit.freedesktop.org/systemd/systemd/tree/src/core/macros.systemd.in)) which are only supported by the official RPM tooling and not by `cargo generate-rpm`. In the case of RPMs it might be less complicated than with DEBs as the official systemd scriptlets for RPMs look pretty trivial. There's also another issue with `cargo generate-rpm` in that it takes pre and post install commands but only as a string, not as a file, so in my PoC I installed a script to /tmp/ and then executed it from the post install command, not ideal and also would require the script to clean itself up afterwards! Ideally `cargo generate-rpm` would be minimally extended to take a file path as input for the pre/post install scripts, not just a command string.
