### ISSUE TITLE
Fatal startup errors not logged?

### ISSUE THREAD

**Issue by he32** [NLnetLabs/routinator#554]
Hi,

I start my routinator with

`routinator -c routinator.conf server --detach`

In my latest upgrade/restart attempt to 0.9.0-rc1 (which failed, more on that in a separate issue), routinator failed to start but also failed to log the reason to syslog, it would seem.  Dropping `--detach` from the command revealed the issue:

```
Failed to open store database at /var/db/rpki-cache/repository/store: Permission denied (os error 13)
Is there another Routinator running?
                        
Fatal error. Exiting.
```

Why didn't this show up in syslog?  Lots of other messages from an earlier routinator instance ended up in /var/log/messages, but this one did not.  (The problem was that the directory above was owned by `root`, and I run routinator as `routinator`.)

**Comment by partim** [comment]
First, thank you for testing the release candidate!

There is a test whether the database can be opened before logging is switched, so this error ends up being just printed on stderr. This is kind of what you want if you run the command from a terminal – otherwise it’ll just come back quietly if you are using syslog. I just assumed that the init system would forward this output to syslog, but that doesn’t seem to be the case universally.

I’ll have a look and see if we can initially log to both stderr and whatever has been configured.
