### ISSUE TITLE
Connection closed by foreign host on RHEL VM running Routinator Docker Image

### ISSUE THREAD

**Issue by mohsin106** [NLnetLabs/routinator#593]
Hi,

I'm having an issue connecting to the WebUI on port 9556 when running the Routinator Docker container on RHEL v7.9. I keep getting "ERR_CONNECTION_RESET" error in the browser. I've verified there are no firewalls blocking my access. I stopped the container and used "nc" to open up port 9556 on my RHEL VM, then from a remote machine, I'm able to successfully telnet to port 9556 and send data back and forth. However, when I run the Routinator Docker image as instructed in the Readme it does not connect on port 9556 in the browser.

I then run the same Routinator Docker image on my Ubuntu 18 VM and everything works fine with no issues to get to the WebUI on port 9556. 

I've disabled IP tables, selinux, and firewald on my RHEL VM but no luck. I'm not sure what else could be causing this issue.

**Comment by ximon18** [comment]
I did a quick test with a CentOS 7.9 VM in AWS using latest Docker (installed [using these instructions](https://docs.docker.com/engine/install/centos/#install-using-the-convenience-script)) and copy-pasted the README instructions for using Docker and was able to connect from my local machine via my browser to port 9556 on the AWS VM (and via that to the Routinator process inside the Docker container).

It took a few minutes before http://<IP ADDRESS>:9556/metrics responded with actual metrics rather than "Initial validation ongoing. Please wait." which is normal for Routinator.

I also tried running the Routinator Docker container inside a CentOS 7 LXC container on my Ubuntu 18.04 LTS machine and was able using SSH port forwarding (`ssh -L 9556:127.0.0.1:9556 user@lxccontainer`) to view the web UI of the Routinator container using a browser on my host.

So ... I'm not sure what the problem is, sorry.

Perhaps you could try passing `--net host` to the `docker run` command to cause Routinator to bind directly to the host network interface and see if that helps?

One common issue with Docker is that it doesn't by default support IPv6 so I wonder whether there could be an issue with a connection to the host via IPv6 not being forwarded to the Docker container port?

**Comment by mohsin106** [comment]
Hi @ximon18 , 

Just figured out the resolution today. I had to change the default Docker subnet from 172.17.0.0/16 to 192.168.0.1/24. Just followed [these steps](https://support.hyperglance.com/knowledge/changing-the-default-docker-subnet).

Thank you,
Mohsin

**Comment by ximon18** [comment]
Thanks @mohsin106 for posting back here with the resolution, perhaps that will help someone else in future!
