### ISSUE TITLE
Docker image Action

### ISSUE THREAD

**Issue by bluikko** [NLnetLabs/routinator#641]
At Docker Hub there is no 0.10.0-rc3 at all and 0.10.0 release is missing so far also.

It seems like the Routinator Docker images may be generated manually. It would be nice to have an Action for them so that Docker images are automatically generated by the pipeline, and immediately available for users without wasting human time for such mundane tasks.

**Comment by ximon18** [comment]
Thanks for the notification @bluikko!

Docker images for Routinator are built automatically by Docker Hub. Sometimes the Docker Hub build service can be very slow or fails to build an image. I’ll take a look at what has happened.

Thanks,

Ximon

**Comment by ximon18** [comment]
Hi @bluikko,

Unfortunately it seems that Docker downgraded our account rather than approve our pending application for Open Source status. As such we have lost access to the automated builds feature.

I have just manually built and pushed `nlnetlabs/routinator:v0.10.0` and also tagged it as `nlnetlabs/routinator:latest`.

Thanks for reporting this and apologies for the inconvenience.

If you could confirm that it now works for you I'll close this issue.

Cheers,

Ximon

**Comment by bluikko** [comment]
Yes the `:latest` I got is now 0.10.0.
