### ISSUE TITLE
APT Repository not working with Debian 11 - Bullseye

### ISSUE THREAD

**Issue by cadirol** [NLnetLabs/routinator#670]
Hi
With Debian 11 it is not possible to add the APT Repo, according to your Readme!
See printout:
```
root|rpki1:~$ wget -qO- https://packages.nlnetlabs.nl/aptkey.asc | apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK

root|rpki1:~$ apt update 
----------------- %< -----------------                                                         
Err:4 https://packages.nlnetlabs.nl/linux/Debian bullseye InRelease                                                                         
  403  Forbidden [IP: 2600:9000:2190:ae00:13:56c:3900:93a1 443]
Reading package lists... Done
E: Failed to fetch https://packages.nlnetlabs.nl/linux/Debian/dists/bullseye/InRelease  403  Forbidden [IP: 2600:9000:2190:ae00:13:56c:3900:93a1 443]
E: The repository 'https://packages.nlnetlabs.nl/linux/Debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
As Debian 11 now uses keyrings, maybe there is the problem?!
However, in such a case a different gpg key is needed?

Cheers

**Comment by AlexanderBand** [comment]
Hi @cadirol. Although it seems that the error is due to the `Warning: apt-key is deprecated`, it's actually due to:

```
E: Failed to fetch https://packages.nlnetlabs.nl/linux/Debian/dists/bullseye/InRelease  403  Forbidden [IP: 2600:9000:2190:ae00:13:56c:3900:93a1 443]
```

I'm not sure why the IP you're trying to connect from cannot access packages.nlnetlabs.nl. Could it be a firewall rule? I just tested it on a fresh Bullseye install and it's all fine:


```
# wget -qO- https://packages.nlnetlabs.nl/aptkey.asc | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```

**Comment by cadirol** [comment]
Hmm, strange
There is no firewall in between, and 403 seems more Webserver related.
I'll try IPv4.

**Comment by ximon18** [comment]
Hi @cadirol,

 > E: The repository 'https://packages.nlnetlabs.nl/linux/Debian bullseye InRelease' is not signed.

That looks like an interesting error in your logs, but we're not seeing it on our Debian 11 Bullseye test machines. I don't know if it's a real error or just a consequence of the earlier apparent failure to fetch. Is this problem persistent or was it a one time failure to fetch? I wonder because AWS had some problems very recently and while I don't believe it affected AWS CloudFront (which we use) the timing is coincidental.

What does your APT sources entry for NLnet Labs look like?

Ximon

**Comment by cadirol** [comment]
hi 
now i've testst the both commands (`apt-key add` and Repo Adding) on a initial installed Debian bullseye VM without issues.  
my failed Tasks above was on a dist-upgraded VM from Debian Buster to bullseye!  
But in my point of view, this should not be an issue?! 

> What does your APT sources entry for NLnet Labs look like?
```
root|rpki1:~$ cat /etc/apt/sources.list.d/routinator.list 
deb [arch=amd64] https://packages.nlnetlabs.nl/linux/Debian/ bullseye main

```

Thank you

**Comment by cadirol** [comment]
Holy sh**
After pasting the content of the apt source file, i recognised the upper case "D" in Debian!
with a small "d" in debian all is working!  

The Background: the sources file is created with ansible, where "Debian" is inserted by Ansible Host Fact. Now i have to lower the string, and everything should work

In any way, thank you very much for your replies!
Cheer A
