### ISSUE TITLE
Brainstorming of monitoring metrics

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#73]
Now that we have Prometheus monitoring instrumentation, we need to come up with useful metrics to collect and expose.

This is issue is here to collect ideas for such metrics that users will find useful.

**Comment by partim** [comment]
I think we’ll have at least two monitoring modes, one where it only keeps some operational information and one with all sorts of extra stuff that may need additional processing but is useful for a State of RPKI dashboard.

**Comment by AlexanderBand** [comment]
Collected via IRC:
- time since last refresh
- time until next refresh
- number of roas
- number of tals
- memory usage
- count of rsync invocations per target url
- duration of last sync per target url
- number of connected sessions from routers
- uptime
- metrics about the ways in which a roa can be broken
- version number
- last_refresh_successful boolean per tal/rsync target

**Comment by ximon18** [comment]
* serial number - needed for Gantry to be able to compare VRPs between the Routinator and the router RPKI database

**Comment by partim** [comment]
Some of these don’t really make sense as a Prometheus metrics. I will add a new endpoint `/status` instead which will print these in a simple text format.

**Comment by partim** [comment]
We now have everything from the list except for the RTR metrics. I made #179 for that and will close this issue.
