### ISSUE TITLE
Document how to run RTR over SSH.

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#83]
RTR can be run over SSH by proxying the RTR port provided by Routinator through sshd. Research and document the best method to do this.

**Comment by wk** [comment]
Tested on IOS-XR, this does not appear to currently work with `routinator` alone out of the box as the implementation expects to be handed an ssh subsystem that's essentially an RTR TCP socket as STDIN/STDOUT

IOS-XR configuration:

```text
router bgp 65534
 rpki server 192.168.0.1
  username rpki
  password rpki
  transport ssh port 22
```

The user `rpki` with password `rpki` exists on the target host 192.168.0.1, the host runs `routinator` with the command line `routinator rtrd -a -l 127.0.0.1:3323`.

This configuration leads to:
* IOS-XR attempts to connect to the destination IP on the destination port via SSH with the specified username and password
* IOS-XR then attempts to launch the 'rpki-rtr' subsystem (needs to be defined in `sshd` config)
* IOS-XR then attempts to talk TCP RTR over stdin/stdout over this session

Since `routinator` currently only offers facilities to listen on TCP RTR on a socket bound to an IP address rather than stdin/stdout, proxying is currently required as a workaround by modifying the `/etc/sshd_config` config file on the host as following:

```text
# Work around antiquated KEX and Ciphers 
# These are required in IOS-XR 5.3 but no longer default in OpenSSH 7.3
Ciphers 3des-cbc
KexAlgorithms diffie-hellman-group1-sha1

# Define an `rpki-rtr subsystem which is actually `netcat` used to proxy STDIN/STDOUT to a running `routinator rtrd -a -l 127.0.0.1:3323`
Subsystem       rpki-rtr        /bin/nc localhost 3323
```

With this configuration, the session comes up correctly:

```text
#show bgp rpki summary
Mon Mar 18 21:15:37.357 UTC

RPKI cache-servers configured: 1
RPKI global knobs
  Origin-AS validation is ENABLED globally
  Origin-AS validity WILL NOT affect bestpath selection globally
  Origin-AS validity signaling towards iBGP is DISABLED globally
RPKI database
  Total IPv4 net/path: 62761/66798
  Total IPv6 net/path: 10890/11909
```

Going forward from here:
* Keep the netcat hack and document this
* Add a mode to `routinator` to offer the RTR TCP protocol on STDIN/STDOUT so that the `routinator` process itself can be bound as rpki-rtr subsystem.

To Do:
* Figure out what JunOS and other implementations do, and how it differs.

**Comment by wk** [comment]
Note that the trade-off may be less deceptively trivial than it appears at first:
* If netcat is used, the routinator listener's availability needs to be assured externally (via e.g. systemd unit, upstart, or similar)
* If routinator is used directly and RTR is available over STDIN/STDOUT, a *new routinator process* will be spawned for each incoming connection, as the same user, and touching the same configuration/data directory - so concurrency, updates, etc. need to be handled constructively.

**Comment by wk** [comment]
While [RFC6810](https://tools.ietf.org/html/rfc6810#page-17) defines a number of optional secure transports for rpki-rtr, [RFC7128](https://tools.ietf.org/html/rfc7128#page-7) suggests that none of the secure transport mechanisms have been widely implemented, with only the SSH implementation seeing any adoption at all. 

This suggests that the IOS-XR implementation may well be the only widely available client that makes use of the SSH transport.
