### ISSUE TITLE
Cannot use --enable-aspa option

### ISSUE THREAD

**Issue by yushoyamaguchi** [NLnetLabs/routinator#883]
In latest version today, I cannot use `--enable-aspa` option.
In addition, I think other options like `--disable-rsync` are not available now.
Please tell me how options have been changed in these days.

**Comment by partim** [comment]
ASPA support has been moved behind a feature flag because it may still change. We don’t want people that never upgrade to accidentally get stuck with an outdated profile version.

To compile with ASPA support, you need to include the `aspa` feature when building by using the `--features aspa` option with `cargo build` or `cargo install`. E.g., to build from a checked out source tree:

```
cargo build --release --locked --features aspa
```

**Comment by partim** [comment]
Oh, `--disable-rsync` does work here.

**Comment by yushoyamaguchi** [comment]
I'm sorry.
I couldn't confirm `--disable-rsync` accurately.

**Comment by yushoyamaguchi** [comment]
When using Routinator whose commit num is `2b450d0`, Routinator could read ASPA object in krill testbed.
However, latest version Routinator couldn't.
Have you changed implementation of reading ASPA?
I use RRDP.

**Comment by partim** [comment]
Yes. The ASPA specification has changed. Krill doesn’t support this new specification yet.

**Comment by yushoyamaguchi** [comment]
Thank you.
If you don't mind, please tell me the changed part of ietf-draft.

**Comment by timbru** [comment]
Hi,

I added a warning to the Krill documentation:
https://krill.docs.nlnetlabs.nl/en/stable/manage-aspas.html

Essentially the optional AFI limit for provider ASNs is dropped in the updated ASPA profile, and as a result, the ASN.1 structure was simplified. Because it's still very early days for ASPA adoption, the feeling (also expressed in the sidrops  IETF working group) was that it would be okay to have a breaking change.

Once Krill 0.14.0 is out (expected around September), it will support the V1 ASPA profile.

**Comment by yushoyamaguchi** [comment]
Thank you very much for teaching me and developing to support new ASPA.
