### ISSUE TITLE
Grafana Dashboard Angular deprecated

### ISSUE THREAD

**Issue by hawbirr** [NLnetLabs/routinator#947]
hi there, 
I was wondaring if there is any chance to update the Grafana dashboard, as we get the following alering from grafana.
"""
Legacy alert rules are deprecated

You have legacy alert rules in this dashboard that were deprecated in Grafana 11 and are no longer supported.
"""
**Angular** plugin

This plugin uses a deprecated, legacy platform based on AngularJS and will stop working in future releases of Grafana.
"""

as it turns out grafana no longer support Angular any more and they have move to **React**.

we are wondering if there will be an update for the dashboard?

<img width="949" alt="image" src="https://github.com/NLnetLabs/routinator/assets/72047317/35a41755-1bf4-468b-9a26-d5634845c51f">

<img width="889" alt="image" src="https://github.com/NLnetLabs/routinator/assets/72047317/fcbb32b0-963a-4a4a-b094-cf7db18ef718">

[Angular support deprecation](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/#angular-support-deprecation)

Thank you for your hard and amazing work.
Regards,
Hawbir

**Comment by M0NsTeRRR** [comment]
Hello,

Have you started working on it? I would be happy to contribute and migrate the existing dashboard if you haven't started yet.
Let me know :)

**Comment by M0NsTeRRR** [comment]
Hello,

No worries :)

I've migrated the dashboard (without adding new metrics) but it's a good starting point for another iteration if someone wants to delve into it.

A few points to note:
- I've added an instance variable to handle multiple Routinator metrics from different RPKI instances.
- I've removed the Rsync statistics in "Update Duration" and "Connection Status" as I can't correlate them to the repository variable.
- I've removed the alert dashboard, as Routinator doesn't provide any Prometheus rules in its documentation. This could lead to confusion, as currently, it reports every alert from alertmanager without filtering.

Dashboard :
[Routinator 0.9.0 and newer-1713777953543.json](https://github.com/NLnetLabs/routinator/files/15060655/Routinator.0.9.0.and.newer-1713777953543.json)

I didn't create a PR because I only see the dashboard on the Grafana website, but I could do it if you tell me where.
I let you tell me if it's look good for you and if so, you can update the dashboard on grafana website :)

Regards,
PS : Thanks to NLnetLabs for the amazing open source work :)

Screenshots :
![image](https://github.com/NLnetLabs/routinator/assets/37785089/fa8e8fa7-76c9-4653-90a3-46aee2bac77a)
![image](https://github.com/NLnetLabs/routinator/assets/37785089/7e9a8ad1-694a-46ec-a9e9-7b451a973d14)

**Comment by AlexanderBand** [comment]
Hi @M0NsTeRRR! I just spun up a Grafana box point at a local Routinator and [the one running at the RIPE NCC](http://rpki-validator.ripe.net/metrics) to test out your dashboard. It's great, thanks so much!

<img width="620" alt="Screenshot 2024-04-22 at 15 56 48" src="https://github.com/NLnetLabs/routinator/assets/3448859/61c22f55-217c-46d9-aa9b-7eea746033de">

You made excellent calls on the instance variable, rsync stats and alerts dashboard. It's much better this way. I'm happy to replace the Routinator dashoard on Grafana.com with your version and credit you. Please send me a message via alex@nlnetlabs.nl with your address details if you would like some awesome stickers.

All the best! 💚

**Comment by M0NsTeRRR** [comment]
Awesome, thank you! 🚀

**Comment by M0NsTeRRR** [comment]
Not with the metrics exposed by routinator. Check on `/metrics` you will see all routinator metrics.

To achieve that you could create an external exporter to retrieve this data based on routinator API

**Comment by AlexanderBand** [comment]
To monitor specific ASNs and prefixes I recommend running [BGPAlerter](https://github.com/nttgin/BGPalerter).

**Comment by M0NsTeRRR** [comment]
I think the issue can be closed ? @AlexanderBand
